services:
  backend:
    image: yur14/todos-backend:latest
    container_name: todos-backend
    restart: unless-stopped
    ports:
      - "5050:5050"
    env_file:
      - .env

  frontend:
    image: yur14/todos-frontend:latest
    container_name: todos-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
